?start: program

program: statement* -> prg

?statement: "let" IDENTIFIER "=" expression ";" -> asn

?expression: term
           | expression "+" term -> add
           | expression "-" term -> sub

?term: factor
     | term "*" factor -> mul
     | term "/" factor -> div

?factor: NUMBER -> num
       | "(" expression ")"

%import common.NUMBER
%import common.WS
%import common.CNAME -> IDENTIFIER

%ignore WS
